# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  version: 3.19
  build: 1

steps:
- script: sudo apt-get install libx11-dev xorg-dev freeglut3-dev libudev-dev 
    libopenal-dev libvorbis-dev libpthread-stubs0-dev libflac++-dev
  displayName: 'Install libaries'
  
- script: |
    mkdir ~/temp
    cd ~/temp
    wget https://cmake.org/files/v$(version)/cmake-$(version).$(build).tar.gz
    tar -xzvf cmake-$(version).$(build).tar.gz
    cd cmake-$(version).$(build)/
    ./bootstrap
    make 
    sudo make install
  displayName: 'Install Cmake'

- script: |
    mkdir build
    cd build
    cmake ..
    make
  displayName: 'Run Cmake'

- script: build/unitTests/unitTests
  displayName: "UnitTest"
